### ISSUE TITLE
CI red since 2025-11-15: TS2344 in src/core/Database.ts (Type 'T' does not satisfy Record<string, GraphEntity>)

### ISSUE THREAD

**Issue by michaeloboyle** [michaeloboyle/sqlite-graph#9]
CI has been failing on main since 2025-11-15 across all Node matrix versions (18/20/22).

```
src/core/Database.ts(471,88): error TS2344: Type 'T' does not satisfy the constraint 'Record<string, GraphEntity>'.
src/core/Database.ts(472,29): error TS2344: Type 'T' does not satisfy the constraint 'Record<string, GraphEntity>'.
```

Likely a generic missing its constraint (`<T extends Record<string, GraphEntity>>`) or a signature change upstream of these call sites.

Ground-truthed 2026-07-03 during the pkm#531 Node 20 Actions verification (failure predates and is unrelated to the action bumps in #8). Example failing run: https://github.com/michaeloboyle/sqlite-graph/actions/runs/28671018639
